#!/usr/bin/env bash

# Script Description:
# 
###########################################
##### 1. Init ##### 
clear

# Get Directory where script is located
# BASEDIR is the directory where the script is located; CAT_DIR is the directory where the catalogues are located
BASEDIR=$(dirname "$0")
CAT_DIR="${BASEDIR}/../catalogues"
TEMP_DIR=${BASEDIR}
echo "BASEDIR: $BASEDIR"

# Change Shell execution to the place where the script lies
cd "$BASEDIR"

# Path to stilts program
stilts_dir="${BASEDIR}/stilts.jar"


############################################################
##### 2. Define input paths from the previous output #####
cat_o1="${TEMP_DIR}/tmp_sdss.fits"  #optical catalogue1
cat_sdss_hz="${TEMP_DIR}/tmp_sdssz3.fits"
cat_r1="${TEMP_DIR}/tmp_first.fits" # radio catalogue1
cat_r2="${TEMP_DIR}/tmp_nvss.fits"  # radio catalogue2
cat_r3="${TEMP_DIR}/tmp_gleam.fits" # radio catalogue3
cat_r4="${TEMP_DIR}/tmp_racs.fits"  # radio catalogue4
############################################################
# 3. Conduct the first matching
## 3.1 Set the matching radius for different catalogues and join type
raidus_r1o1=3   # First 5"
raidus_r2o1=25  # NVSS 45"
raidus_r3o1=110 # gleam psfmaj <200"
raidus_r4o1=15  # RACS 25"
# jointype=1and2  

java -jar $stilts_dir tmatch2  in1="${cat_r1}" in2="${cat_o1}" out=match1_r1o1.fits \
                               values1="RA_deg DEC_deg" values2="RA DEC"  \
                               matcher=sky params="$raidus_r1o1" \
                               join="1and2" find="all" \
                               fixcols=all suffix1=_r1 suffix2=_o1
echo "---> Crossmatched R1O1"

java -jar $stilts_dir tmatch2 in1="${cat_r2}" in2="${cat_o1}" out=match1_r2o1.fits \
                               values1="RA_deg DEC_deg" values2="RA DEC" \
                               matcher=sky params="$raidus_r2o1" \
                               join="1and2" find="all" \
                               fixcols=all suffix1=_r2 suffix2=_o1
echo "---> Crossmatched R2O1"

java -jar $stilts_dir tmatch2 in1="${cat_r3}" in2="${cat_o1}" out=match1_r3o1.fits \
                               values1="RA_deg DEC_deg" values2="RA DEC"  \
                               matcher=sky params="$raidus_r3o1" \
                               join="1and2" find="all" \
                               fixcols=all suffix1=_r3 suffix2=_o1
echo "---> Crossmatched R3O1"

java -jar $stilts_dir tmatch2 in1="${cat_r4}" in2="${cat_o1}" out=match1_r4o1.fits \
                               values1="RA_deg DEC_deg" values2="RA DEC"  \
                               matcher=sky params="$raidus_r4o1" \
                               join="1and2" find="all" \
                               fixcols=all suffix1=_r4 suffix2=_o1
echo "---> Crossmatched R4O1"



exit
