#!/usr/bin/env bash

# Author: 	Yingkang Zhang
# E-Mail: 	ykzhang@shao.ac.cn
# Date: 	2025-2-14
# Institution:	SHAO - Shanghai Astronomical Observatory, CAS, China
#		        CSIRO, Australia

# This template is from Fabio Luchsinger and mofiied by Yingkang Zhang. 
# I learn this from the CSIRO's co-learnium program during the work in CSIRO Space & Astronomy.


# Script Description:

############################################################
##### 1. Init ##### 
clear

# Get Directory where script is located
BASEDIR=$(dirname "$0")
CAT_DIR="${BASEDIR}/../catalogues"
echo "BASEDIR: $BASEDIR"

# Change Shell execution to the place where the script lies
cd "$BASEDIR"

# Path to stilts program
stilts_dir="${BASEDIR}/stilts.jar"


############################################################
##### 2. Define input paths #####
SDSSdr16q="${CAT_DIR}/DR16Q_v4.fits"
SDSS16_galaxy="${CAT_DIR}/dr16_galaxy_all.fits"
FIRSTcat="${CAT_DIR}/first14.fits"
NVSScat="${CAT_DIR}/nvss.fits"
GLEAMcat="${CAT_DIR}/gleam_full.fits"
RACScat="${CAT_DIR}/racs1.fits"
echo "SDSSdr16q: $SDSSdr16q"

# if you want to start from the tmp fits files rather than the original catalogues (i.e. start from script2), you can uncomment the following lines and comment the above lines
# This is useful if you work on different machines and do not have the original catalogues in other machines, just the tmp files can be stored in the git repository
# FIRSTcat="tmp_first.fits"
# NVSScat="tmp_nvss.fits"
# GLEAMcat="tmp_gleam.fits"
# RACScat="tmp_racs.fits"
############################################################
## 3. compress the sdss catalogue ##########################
Cols_SDSSdr16q='keepcols "SDSS_NAME RA DEC Z SOURCE_Z Z_PIPE ZWARNING Z_VI Z_CONF \
                          IS_QSO_QN Z_QN Z_10K Z_CONF_10K Z_PCA ZWARN_PCA"'
qso_cols='addcol class "\"QSO\""'
### 3.1 reduce the columns for sdssdr16q
#Make the new sdss16cat by concatenating the sr16q and galaxies from sdss16
java -jar $stilts_dir tpipe ifmt=fits "$SDSSdr16q" \
                            cmd="$Cols_SDSSdr16q" \
                            cmd="$qso_cols" \
                            out=tmp_sdss.fits

### 3.2
# cols_dr16g='keepcols "SDSS_NAME RA DEC Z ZWARNING class"'
# java -jar  $stilts_dir tpipe ifmt=fits "$SDSS16_galaxy" \
#                              cmd="$cols_dr16g" \
#                              out=tmp_sdss16g.fits

# Concatenate the two sdss catalogues
# I did this in python this time. Which is easier (it is also easy in topcat).
# you can comment that and run the python script along to release the memory burden
# python concat_cat.py
dr16_comb="tmp_sdss16_comb.fits"
dr16_comb_out="tmp_sdss16_qg.fits"

cols_dr16='keepcols "SDSS_NAME RA DEC class Z SOURCE_Z Z_PIPE ZWARNING Z_VI Z_CONF \
                      IS_QSO_QN Z_QN Z_10K Z_CONF_10K Z_PCA ZWARN_PCA"'
java -jar  $stilts_dir tpipe ifmt=fits "$dr16_comb" \
                             cmd="$cols_dr16" \
                             out="$dr16_comb_out"

### 3.3 make the highz catalogue of dr16q for further usage
java -jar $stilts_dir tpipe ifmt=fits "$SDSSdr16q" \
                            cmd="$Cols_SDSSdr16q" \
                            cmd='select "z > 3"' \
                            out=tmp_sdssz3.fits

############################################################
# 4. Compress the radio catalogues
# keep only the columns that are needed for crossmatching (e.g. position and its error, psf, representative flux density)
sex_to_deg='addskycoords -inunit sexagesimal -outunit degrees fk5 icrs RAJ2000 DEJ2000 RA_deg DEC_deg'
deg_to_deg='addskycoords -inunit degrees -outunit degrees fk5 icrs RAJ2000 DEJ2000 RA_deg DEC_deg'

Cols_first14='keepcols "FIRST RA_deg DEC_deg Fpeak Fint Rms Maj Min PA"'

Cols_nvss='keepcols "NVSS RA_deg e_RAJ2000 DEC_deg e_DEJ2000 S1.4 e_S1.4 MajAxis MinAxis"'

Cols_gleam='keepcols "GLEAM RA_deg e_RAJ2000 DEC_deg e_DEJ2000 Fpwide e_Fpwide Fintwide e_Fintwide \
                      awide e_awide bwide e_bwide pawide psfawide psfbwide psfPAwide"'

Cols_racs='keepcols "RACS-DR1 RA_deg e_RAJ2000 DEC_deg e_DEJ2000 Ftot e_Ftot Fpk e_Fpk amaj bmin e_amaj e_bmin PA e_PA amaj0 bmin0 PA0 \
                      e_amaj0 e_bmin0 e_PA0"'
                     
java -jar $stilts_dir tpipe ifmt=fits "$FIRSTcat" \
                            cmd="$sex_to_deg" \
                            cmd="$Cols_first14" \
                            out=tmp_first.fits

java -jar $stilts_dir tpipe ifmt=fits "$NVSScat" \
                            cmd="$sex_to_deg" \
                            cmd="$Cols_nvss" \
                            out=tmp_nvss.fits

java -jar $stilts_dir tpipe ifmt=fits "$GLEAMcat" \
                            cmd="$deg_to_deg" \
                            cmd="$Cols_gleam" \
                            out=tmp_gleam.fits

java -jar $stilts_dir tpipe ifmt=fits "$RACScat" \
                            cmd="$deg_to_deg" \
                            cmd="$Cols_racs" \
                            out=tmp_racs.fits

echo "If you are starting from the tmp fits files, you can ignore the above errors"
exit
