#!/usr/bin/env bash

# Script Description:
# 
###########################################
##### 1. Init ##### 
clear

# Get Directory where script is located
# BASEDIR is the directory where the script is located; CAT_DIR is the directory where the catalogues are located
BASEDIR=$(dirname "$0")
CAT_DIR="${BASEDIR}/../catalogues"
TEMP_DIR=${BASEDIR}
echo "BASEDIR: $BASEDIR"

# Change Shell execution to the place where the script lies
cd "$BASEDIR"

# Path to stilts program
stilts_dir="${BASEDIR}/stilts.jar"


############################################################
##### 2. Define input paths from the previous output #####
cat_o1="${TEMP_DIR}/tmp_sdss.fits"  #optical catalogue1
cat_sdss_hz="${TEMP_DIR}/tmp_sdssz3.fits"
cat_r1="${TEMP_DIR}/tmp_first.fits" # radio catalogue1
cat_r2="${TEMP_DIR}/tmp_nvss.fits"  # radio catalogue2
cat_r3="${TEMP_DIR}/tmp_gleam.fits" # radio catalogue3
cat_r4="${TEMP_DIR}/tmp_racs.fits"  # radio catalogue4
############################################################
# 3. Conduct the first matching
## 3.1 Set the matching radius for different catalogues and join type
raidus_o1r1=3   # First 5"
raidus_o1r2=25  # NVSS 45"
raidus_o1r3=100 # gleam psfmin <200"
raidus_o1r4=15  # RACS 25"
# jointype=1and2  

java -jar $stilts_dir tmatch2 "${cat_o1}" "${cat_r1}" out=match1_o1r1.fits \
                               values1="RA DEC" values2="RA_deg DEC_deg" \
                               matcher=sky params="$raidus_o1r1" \
                               join="1and2" find="all" \
                               fixcols=all suffix1=_o1 suffix2=_r1
echo "---> Crossmatched O1R1"

java -jar $stilts_dir tmatch2 "${cat_o1}" "${cat_r2}" out=match1_o1r2.fits \
                               values1="RA DEC" values2="RA_deg DEC_deg" \
                               matcher=sky params="$raidus_o1r2" \
                               join="1and2" find="all" \
                               fixcols=all suffix1=_o1 suffix2=_r2
echo "---> Crossmatched O1R2"

java -jar $stilts_dir tmatch2 "${cat_o1}" "${cat_r3}" out=match1_o1r3.fits \
                               values1="RA DEC" values2="RA_deg DEC_deg" \
                               matcher=sky params="$raidus_o1r3" \
                               join="1and2" find="all" \
                               fixcols=all suffix1=_o1 suffix2=_r3
echo "---> Crossmatched O1R3"

java -jar $stilts_dir tmatch2 "${cat_o1}" "${cat_r4}" out=match1_o1r4.fits \
                               values1="RA DEC" values2="RA_deg DEC_deg" \
                               matcher=sky params="$raidus_o1r4" \
                               join="1and2" find="all" \
                               fixcols=all suffix1=_o1 suffix2=_r4
echo "---> Crossmatched O1R4"



exit
