#!/usr/bin/env bash

# Author: 	Fabio Luchsinger
# E-Mail: 	fabio.luchsinger@idia.ac.za
# Date:		28.8.2023
# Institution:	University of the Western Cape

# Script Description:
# This script shall create a plot 
# of the LOFAR catalogue

##############################
##### Init ##### 
clear

# Get Directory where script is located
BASEDIR=$(dirname "$0")

# Change Shell execution to the place where the script lies
cd "$BASEDIR"

# Path to stilts program
stilts_dir="${BASEDIR}/stilts.jar"

###############################
##### Define input path ##### 

PathLOFAR="${BASEDIR}/lofar-xmmlss.fits"
PathMIGHTEE="${BASEDIR}/MIGHTEE_Continuum_Early_Science_XMMLSS_Level1.fits"

############################################################
##### Create a Plot ##### 

java -jar $stilts_dir plot2sky \
   xpix=544 \
   clon=35.01 clat=-4.51 radius=4.159 \
   legend=false \
   layer=Mark \
      in=$PathLOFAR \
      lon=RAJ2000 lat=DEJ2000 \
      shading=auto out=image2.pdf

java -jar $stilts_dir plot2sky \
   xpix=544 \
   clon=345.9 clat=-11.2 radius= \
   legend=true \
   shading=auto \
   layer_1=Mark \
      in_1=$PathLOFAR \
      lon_1=RAJ2000 lat_1=DEJ2000 \
      color_1=grey \
      leglabel_1='3: All' \
   layer_2=Mark \
      in_2=$PathMIGHTEE \
      lon_2=RA lat_2=DEC \
      color_2=blue \
      leglabel_2='4: All' 