#!/usr/bin/env bash

# Author: 	Fabio Luchsinger
# E-Mail: 	fabio.luchsinger@idia.ac.za
# Date:		28.8.2023
# Institution:	University of the Western Cape

# Script Description:
# This script shall create a plot 
# of the LOFAR catalogue

##############################
##### Init ##### 
clear

# Get Directory where script is located
BASEDIR=$(dirname "$0")

# Change Shell execution to the place where the script lies
cd "$BASEDIR"

# Path to stilts program
stilts_dir="${BASEDIR}/stilts.jar"

###############################
##### Define input path ##### 

PathLOFAR="${BASEDIR}/lofar-xmmlss.fits"

############################################################
##### Create a Plot ##### 

java -jar $stilts_dir plot2sky \
   xpix=544 \
   clon=35.01 clat=-4.51 radius=4.159 \
   legend=false \
   layer=Mark \
      in=$PathLOFAR \
      lon=RAJ2000 lat=DEJ2000 \
      shading=auto #out=image.pdf
